### ISSUE TITLE
Implications for HTML

### ISSUE THREAD

**Issue by annevk** [tc39/proposal-resizablearraybuffer#10]
I suspect we want these to be serializable and deserializable. Will this be pretty much identical to the existing buffer types or are there new considerations?

**Comment by syg** [comment]
Good question.

For `ResizableArrayBuffer`, I think it is pretty much identical to the existing buffer types. Since structured clone doesn't call user code, there's no way for the RAB to be resized in the middle of copying.

`GrowableSharedArrayBuffer` would need a new path in the algorithm. Currently, since SABs are fixed size, the serialization serializes both the [[ArrayBufferData]] and [[ArrayBufferByteLength]] slots. For GSABs, since the byte length itself is now shared, this new path would need to serialize both the data block that contains the actual data of the backing store and the data block that contains the shared length. From the spec's perspective there're no races here: getting the data block isn't a shared memory operation, and the data block never changes in the spec draft. From the implementation's perspective, the backing store pointer of GSABs (like growable shared wasm memories) ought to never change, so that should be fine as well, I think?

**Comment by annevk** [comment]
Yeah, I wasn't really able to spot any obvious difficulties myself. It might be worth calling serialization and deserialization out in the README so other folks will try to think through it as well.

**Comment by annevk** [comment]
Oh so, StructuredSerializeInternal can invoke scripts, e.g., if there are getters in the data being cloned. I'm not sure if that matters, but it's not true that no user code is involved here.

**Comment by annevk** [comment]
Any updates here? Given that https://webidl.spec.whatwg.org/#AllowResizable is done it seems like it would be good to cover this too.

**Comment by syg** [comment]
I've created https://github.com/whatwg/html/pull/8559.

> Oh so, StructuredSerializeInternal can invoke scripts, e.g., if there are getters in the data being cloned. I'm not sure if that matters, but it's not true that no user code is involved here.

For resizable (and fixed-length) buffers it doesn't look to me like any user code is involved in the middle of its own serialization, since the length is read off internal slots. In general of course you are correct.

**Comment by ljharb** [comment]
The proposal has reached stage 4.
