### ISSUE TITLE
Setting [[ArrayBufferByteLength]] in resize and grow seems to be missing / incorrect

### ISSUE THREAD

**Issue by marjakh** [tc39/proposal-resizablearraybuffer#19]
1) GrowableSharedArrayBuffer.prototype.grow has these lines:

Let _byteLengthBlock_ be _O_.[[ArrayBufferByteLength]].
Perform SetValueInBuffer(_byteLengthBlock_, 0, Uint64, _newByteLength_, *true*, SeqCst).

SetValueInBuffer signature: SetValueInBuffer ( arrayBuffer, byteIndex, type, value, isTypedArray, order [ , isLittleEndian ] )

so arrayBuffer would be _byteLengthBlock_ which doesn't sound correct, as _byteLengthBlock_ (despite the name) is a number.

Are these supposed to set [[ArrayBufferByteLength]]?

Should this be just:
Set _O_.[[ArrayBufferByteLength] to _newByteLength_.

---

2) In ResizableArrayBuffer.prototype.resize, setting [[ArrayBufferByteLength]] seems to be missing altogether.

**Comment by syg** [comment]
1.

> Are these supposed to set [[ArrayBufferByteLength]]?

No, because the length of a GSAB is concurrently accessible from different threads, so in the spec, it lives in its own shared data block. The current spec draft is still wrong though, and it should be getting the block from the [[ArrayBufferByteLengthData]], which GSABs have instead of an [[ArrayBufferByteLength]].

> 2. In ResizableArrayBuffer.prototype.resize, setting [[ArrayBufferByteLength]] seems to be missing altogether.

Good catch, will fix.
