### ISSUE TITLE
Make `transfer` argument optional

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-resizablearraybuffer#7]
I think a common case for `arrayBuffer.transfer` will be to take ownership of a whole buffer. I'd like to propose that if you don't pass any argument it behaves the same as if you had passed `byteLength`.

(Also, I see it says "Throws a RangeError unless 0 < newByteLength < this.byteLength." - should those be "<="?)

**Comment by ljharb** [comment]
https://github.com/domenic/proposal-arraybuffer-transfer/ seems to not require this argument; this seems like a good idea.

**Comment by syg** [comment]
I agree, this seems useful. I'll change the proposal soonish, calling it a day today.

**Comment by syg** [comment]
> (Also, I see it says "Throws a RangeError unless 0 < newByteLength < this.byteLength." - should those be "<="?)

This was just wrong, there's no restriction for `transfer` to be `< this.byteLength`. But the `0 <` part isn't a typo, though it's a bit of an open question: should you be allowed to transfer into a detached-at-construction AB?

For transfer, I agree this should be relaxed to `0 <=`, since there's no good reason to disallow transferring into a detached-at-construction buffer.
